name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-checks:
    name: Frontend Checks
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'  # Automatic caching for npm and node_modules

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run lint checks
      - name: Lint frontend code
        run: npm run lint

      # 5️⃣ Run tests
      - name: Run frontend tests
        run: npm test

      # 6️⃣ Optional: Build step (if your frontend has one)
      - name: Build frontend
        run: npm run build
        if: ${{ success() }}

      # 7️⃣ Optional: Type checking
      - name: Type check
        run: npm run typecheck
        if: ${{ success() }}
